---
title: "Projecten ICT Dashboard Rijk"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---


```{r global, include=FALSE}
library(flexdashboard)
library(jsonlite)
library(stringr)
library(data.table) 
library(curl)
library(ggplot2)
library(knitr)
library(ggrepel)
library(shiny)

# load data in 'global' chunk so it can be shared by all users of the dashboard
ict.das <- read.csv2("O:/Open_data/ICT_Dashboard/data/2017-08-30_ICT_dashboard.csv")

# Colours Netherlands Court of Audit
myColours = data.frame(hex=c("#25257A","#00BCDF","#A2A419","#BE5900","#5C332A","#741672","#BE0034","grey","white"),
                       color=c("dark blue","light blue","moss green","orange","brown","purple","red","grey", "white"),
                       stringsAsFactors = F)

stat.col <- data.frame(project_status=unique(ict.das$project_status),
                       hex=myColours[c(3,4,2,6),]$hex,
                       col=myColours[c(3,4,2,6),]$col,
                       stringsAsFactors = F)

```


Column {.sidebar}
-----------------------------------------------------------------------

Selecteer de projectstatus en de maximale daadwerkelijke kosten van de te tonen projecten.

```{r}

checkboxGroupInput("pr_stat", "Status project", as.character(stat.col$project_status), 
            selected = as.character(stat.col$project_status))

sliderInput("pr_cost", label = "Maximale kosten",
            min = 0, max = 300, value = 300, step = 50)

ict.das.sub <- reactive(subset(ict.das,
                         (daadwerkelijk_totaal_projectkosten.z >= 0 &
                         daadwerkelijk_totaal_projectkosten.z <= input$pr_cost &
                         actueel_totaal_projectkosten.a >= 0 &
                         actueel_totaal_projectkosten.a <= input$pr_cost) &
                         project_status %in% input$pr_stat))

max.cost <- reactive(input$pr_cost)
  
```

Het dashboard toont projecten waarvan de (tot nu toe) gerealiseerde kosten kleiner zijn dan `r max.cost` miljoen euro.




Column {data-width=400}
-----------------------------------------------------------------------

### Initieel verwachtte kosten vs daadwerkelijke kosten

```{r}
renderPlot({
 
 ict.das.sel <- ict.das.sub()

  ggplot(ict.das.sel, aes(x=actueel_totaal_projectkosten.a,
                         y=daadwerkelijk_totaal_projectkosten.z,
                         color=project_status,
                         label=naam)) +
   geom_segment(aes(x = 0, y = 0, xend = input$pr_cost, yend = input$pr_cost),color="lightgrey",size=0.25) +
   geom_point(aes(colour=factor(project_status)),size=4,alpha=0.8) + 
   geom_text_repel(data=subset(ict.das.sel,verschil_abs >= 0.20*input$pr_cost), 
                   aes(x=actueel_totaal_projectkosten.a,
                       y=daadwerkelijk_totaal_projectkosten.z),
                   size=5,
                   color="black",
                   nudge_x = 4) +
   scale_color_manual(breaks = unique(ict.das.sel$project_status),
                      values=stat.col[stat.col$project_status %in% unique(ict.das.sel$project_status),]$hex) +
   labs(x="Projectkosten eerste herijking (mln)",
        y="Projectkosten laatste herijking (mln)",
        title="Projecten ICT dashboard Rijk",
        subtitle=paste("(Kosten tussen", 0, "en", input$pr_cost,
                       "mln, ", Sys.Date(),")")) +
   theme_minimal(base_size=15) +
   theme(legend.position="bottom") +
   theme(legend.title=element_blank()) +
   coord_fixed(ratio=1)
})
```

Column {data-width=600}
-----------------------------------------------------------------------

### Top 10 projecten met de grootste absolute overschrijding

```{r}
renderTable({
  
  ict.das.sel <- ict.das.sub()
  
  v.abs <- ict.das.sel[order(-ict.das.sel$verschil_abs),][1:10,c(2,3,5,4,13,10,14,17)]
  names(v.abs) <- c("naam","status","ministerie","startdatum","actuele einddatum", "kosten 1e herijking",
                       "kosten laatste herijking", "absoluut verschil")
  v.abs
}, digits = 0)
```

### Top 10 projecten met de grootste procentuele overschrijding

```{r}

renderTable({
  
  ict.das.sel <- ict.das.sub()
  ict.das.sel <- ict.das.sel[!is.infinite(ict.das.sel$verschil_per),]
  
  v.rel <- ict.das.sel[order(-ict.das.sel$verschil_per),][1:10,c(2,3,5,4,13,10,14,18)]
  colnames(v.rel) <- c("naam","status","ministerie","startdatum","actuele einddatum", "kosten 1e herijking",
                       "kosten laatste herijking", "verschil %")
  v.rel
}, digits = 0)

```
